name: Build and Archive iOS Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      # Шаг 1: Клонирование репозитория
      - name: Checkout source code
        uses: actions/checkout@v3

      # Шаг 2: Настройка Xcode
      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 16.1

      # Шаг 3: Сборка xcarchive
      - name: Build xcarchive
        run: |
          xcodebuild clean archive \
          -project EasyMusic.xcodeproj \
          -scheme EasyMusic \
          -configuration Release \
          -archivePath ./build/EasyMusic.xcarchive \
          -destination "generic/platform=iOS" \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_ALLOWED=NO
          - name: Check archive contents
          run: |
          ls -la ./build/EasyMusic.xcarchive
          ls -la ./build/EasyMusic.xcarchive/Products/Applications
          ls -la ./build/EasyMusic.xcarchive/dSYMs
      # Шаг 4: Сохранение xcarchive как артефакт
      - name: Upload xcarchive as artifact
        uses: actions/upload-artifact@v3
        with:
          name: EasyMusic.xcarchive
          path: ./build/EasyMusic.xcarchive

      # Шаг 5: Добавление инструкции по созданию .ipa
      - name: Upload instructions
        run: echo "To create .ipa:\n1. Open Xcode Organizer or use xcodebuild.\n2. Use xcarchive to generate .ipa.\n3. For manual export, run:\nxcodebuild -exportArchive -archivePath ./EasyMusic.xcarchive -exportPath ./EasyMusic.ipa -exportOptionsPlist ./ExportOptions.plist" > README_FOR_IPA.txt
      - name: Upload README
        uses: actions/upload-artifact@v3
        with:
          name: README_FOR_IPA
          path: README_FOR_IPA.txt
